version: "3.3"
services:
  api-balancerExamen:
    build: ./../api-loadbalancer/
    ports:
      - "2000:80"
    depends_on:
      - apiExamen1
      - apiExamen2
      - apiExamen3
      - apiExamen4
      - apiExamen5
      - apiExamen6
  apiExamen1:
    build: ./
    ports:
      - "2001:2000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Channel123*"
      DATABASE_OPTION_DATABASE: "TodosDB"
      API_PORT: "2000"
      SERVER_TAG: "apiExamen1"
    depends_on:
      - db
    links:
      - "db"
  apiExamen2:
    build: ./
    ports:
      - "2002:2000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Channel123*"
      DATABASE_OPTION_DATABASE: "TodosDB"
      API_PORT: "9000"
      SERVER_TAG: "apiExamen2"
    depends_on:
      - db
    links:
      - "db"
  apiExamen3:
    build: ./
    ports:
      - "2003:2000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Channel123*"
      DATABASE_OPTION_DATABASE: "TodosDB"
      API_PORT: "2000"
      SERVER_TAG: "apiExamen3"
    depends_on:
      - db
    links:
      - "db"
  apiExamen4:
    build: ./
    ports:
      - "2004:2000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Channel123*"
      DATABASE_OPTION_DATABASE: "TodosDB"
      API_PORT: "2000"
      SERVER_TAG: "apiExamen4"
    depends_on:
      - db
    links:
      - "db"
  apiExamen5:
    build: ./
    ports:
      - "2005:2000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Channel123*"
      DATABASE_OPTION_DATABASE: "TodosDB"
      API_PORT: "2000"
      SERVER_TAG: "apiExamen5"
    depends_on:
      - db
    links:
      - "db"
  apiExamen6:
    build: ./
    ports:
      - "2006:2000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Channel123*"
      DATABASE_OPTION_DATABASE: "TodosDB"
      API_PORT: "2000"
      SERVER_TAG: "apiExamen6"
    depends_on:
      - db
    links:
      - "db"
  db:
    image: "mcr.microsoft.com/mssql/server"
    user: "0:0"
    hostname: "sqlserver"
    environment:
      SA_PASSWORD: "Channel123*"
      ACCEPT_EULA: "Y"
    volumes:
      - data:/var/opt/mssql/data
volumes:
  data:
