version: "3.3"
services:
  api-balancerexamen:
    build: ./../api-loadbalancer/
    ports:
      - "2000:80"
    depends_on:
      - api-examen1
      - api-examen2
      - api-examen3
      - api-examen4
      - api-examen5
      - api-examen6
  api-examen1:
    build: ./
    ports:
      - "2001:2000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Channel123*"
      DATABASE_OPTION_DATABASE: "TodosDB"
      API_PORT: "2000"
      SERVER_TAG: "api-examen1"
    depends_on:
      - db
    links:
      - "db"
  api-examen2:
    build: ./
    ports:
      - "2002:2000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Channel123*"
      DATABASE_OPTION_DATABASE: "TodosDB"
      API_PORT: "9000"
      SERVER_TAG: "api-examen2"
    depends_on:
      - db
    links:
      - "db"
  api-examen3:
    build: ./
    ports:
      - "2003:2000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Channel123*"
      DATABASE_OPTION_DATABASE: "TodosDB"
      API_PORT: "2000"
      SERVER_TAG: "api-examen3"
    depends_on:
      - db
    links:
      - "db"
  api-examen4:
    build: ./
    ports:
      - "2004:2000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Channel123*"
      DATABASE_OPTION_DATABASE: "TodosDB"
      API_PORT: "2000"
      SERVER_TAG: "api-examen4"
    depends_on:
      - db
    links:
      - "db"
  api-examen5:
    build: ./
    ports:
      - "2005:2000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Channel123*"
      DATABASE_OPTION_DATABASE: "TodosDB"
      API_PORT: "2000"
      SERVER_TAG: "api-examen5"
    depends_on:
      - db
    links:
      - "db"
  api-examen6:
    build: ./
    ports:
      - "2006:2000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Channel123*"
      DATABASE_OPTION_DATABASE: "TodosDB"
      API_PORT: "2000"
      SERVER_TAG: "api-examen6"
    depends_on:
      - db
    links:
      - "db"
  db:
    image: "mcr.microsoft.com/mssql/server"
    user: "0:0"
    hostname: "sqlserver"
    environment:
      SA_PASSWORD: "Channel123*"
      ACCEPT_EULA: "Y"
    volumes:
      - data:/var/opt/mssql/data
volumes:
  data:
